language: rust
script:
  - git submodule update --init --recursive
  - cargo build --verbose
  - cargo test --verbose
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
